### ISSUE TITLE
How does attribute presevation in 'attributes' work?

### ISSUE THREAD

**Issue by yxchng** [rohitgandikota/sliders#44]
Can you kindly explain the technical details? For example, what does 'male, female' in attributes do behind the scene that causes these attributes to be preserved?

**Comment by rohitgandikota** [comment]
turns out single direction for some concepts are entangled. So we find a common direction by looking at individual specific directions across attributes. For example instead of looking at "old person" to "young person", we look at a common direction by looking at "male old person" to "male young person" and "female old person" to "female young person"
![Uploading directions.png…]()

Please refer to the appendix of our paper for more info: https://arxiv.org/pdf/2311.12092.pdf
